### ISSUE TITLE
Train Pensieve with Genet on FCC/Norway traces

### ISSUE THREAD

**Issue by NotSpecial** [GenetProject/Genet#6]
Hi!

First of all, great work!

I'd like to experiment with Genet and train a few other variants of Pensieve.
Concretely, I'd like to train Pensieve with some of the FCC and Norway traces.

As far as I can see, this is not supported by the current code, correct?
[I found this file](https://github.com/GenetProject/Genet/blob/main/src/simulator/abr_simulator/pensieve/genet.py), which I believe does the Genet training for Pensieve. However, currently, it only works with synthetic traces.

First of all: is my understanding correct? Or is there some other code that can train Pensieve with other traces and I just haven't found it yet?

If there isn't, I considered modifying [this part of the code](https://github.com/GenetProject/Genet/blob/main/src/simulator/abr_simulator/pensieve/genet.py#L151), i.e. the `black_box_function`, to load existing traces instead of generating them. Would that make sense?

**Comment by lesleychou** [comment]
Hi,

Thank you for your interest. 

Yes, your understanding is correct. Currently, genet was trained on synthetic traces. 

If you just want to add more FCC/Norway traces, you can directly put them in the synthetic traces folder (but the program will still generate the synthetic traces there too). If you want to only train on FCC/Norway traces, feel free to modify the load_trace related functions to match your purpose!

**Comment by NotSpecial** [comment]
Great, thanks for the quick response. I'll try it out!
