### ISSUE TITLE
Problems trying to run the evaluation with Mahimahi.

### ISSUE THREAD

**Issue by NotSpecial** [GenetProject/Genet#7]
Happy new year, everyone!

I'm trying to run some parts of Genets evaluation, specifically the emulated part with Mahimahi.

I followed the installation instructions, but cannot get Mahimahi to run, it always crashes with some permission errors.
I've created [an issue in the Mahimahi repo](https://github.com/ravinet/mahimahi/issues/159) with more details, but I was wondering if you had similar issues with Mahimahi?

Is there any specific configuration/setup I need to to to make it work?

**Comment by zxxia** [comment]
When I saw the permission errors you mentioned, it was usually that I forgot to enable net.ipv4.ip_forward=1. Following Keith's suggestions resolved the permission errors.

You might want to try Ubuntu 16.04LTS or 18.04LTS. I guess they might have better compatibility with Mahimahi?

I will close this issue for now as there is an ongoing discussion in the Mahimahi repo and feel free to reopen it if needed.
